### ISSUE TITLE
Quality Assessment is not filtering

### ISSUE THREAD

**Issue by luisrogerio** [vitorfs/parsifal#39]
The Quality Assessment isn't filtering according with any parameters. The attached image below is a sample when trying to filter by the cutoff score, except that some undone with lower score appears. It is important to notice that they are UNDONE and not checked with the lowest score.
![image](https://cloud.githubusercontent.com/assets/14863928/10776501/312c9050-7cf9-11e5-9e64-348ac0b11067.png)
 
Thank you.

**Comment by vitorfs** [comment]
Thanks for reporting.
I just released a patch to fix it.
