### ISSUE TITLE
Invite co-author not working

### ISSUE THREAD

**Issue by vitorfs** [vitorfs/parsifal#40]

**Comment by mgarzon** [comment]
@vitorfs  is it working now?

**Comment by jairofsouza** [comment]
Sometimes it works, sometimes it doesn't. Using the user id, it doesn't seem to be working at all. Using the user email, one can try luck.

**Comment by vitorfs** [comment]
how to get the co-author invitation to work: 
* visit the author profile (e.g. https://parsif.al/vitor/) and follow her/him
* now go to your SLR and click on the "add author" button
* by clicking on the "contacts" field you should see everyone that you follow
* select the author's name, and click on "send invitation"

this need to be improved, and this issue is sitting here for a long time now.. sorry about that :(
