### ISSUE TITLE
Are there any plans to develop the Library functionality further?

### ISSUE THREAD

**Issue by bradlishman** [vitorfs/parsifal#42]
On both the live site and a version I hosted locally, the library functionality doesn't seem to work as expected.

**Comment by vitorfs** [comment]
Hey there,
It's still under development
It is not available for the general public yet. Even thought some parts of the library is accessible via url "/library/" in the production version. It is not ready to be used

**Comment by bradlishman** [comment]
Thanks for the response Vitor. Any time frame in mind for the next version?
