### ISSUE TITLE
unable to open databasefile

### ISSUE THREAD

**Issue by samazaphikel** [vitorfs/parsifal#45]
![image](https://user-images.githubusercontent.com/35742942/39971564-98d03a32-56fd-11e8-9c4f-b513b1b90c7b.png)

I cant connect to the database

**Comment by vitorfs** [comment]
When using SQLite3 the path to the file must be somewhere your application can reach

You can change that on your `.env` file:

```
DATABASE_URL=sqlite:////tmp/db.sqlite3
```

In the example above it is pointing to the temp folder.

To place it elsewhere, just change the path:

```
DATABASE_URL=sqlite:////Users/vitor/dev/parsifal/parsifal.sqlite3
```
